# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

pod "sqlite3", "~> 3"
pod "Arcane", "~> 0.3"

target 'AtomSDK' do
  use_frameworks!
end

target 'AtomSDKTests' do
    use_frameworks!
end

post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
end
