# Uncomment this line to define a global platform for your project
platform :ios, '9.0'


pod 'sqlite3'
pod 'Arcane', git: 'https://github.com/onmyway133/Arcane'

target 'AtomSDK' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AtomSDK
end

target 'AtomSDKTests' do
    use_frameworks!
    
end

post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
end
