coverage_service: coveralls
xcodeproj: atom-sdk/AtomSDK/AtomSDK.xcodeproj
workspace: atom-sdk/AtomSDK/AtomSDK.xcworkspace
scheme: AtomSDK
source_directory: atom-sdk/AtomSDK/AtomSDK
ignore:
  - Batch.swift