language: objective-c 
osx_image: xcode7.3

 global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=atom-sdk/AtomSDK/AtomSDK.xcworkspace
  - SCHEME=AtomSDK
  - SDK=iphonesimulator9.3
  - DESTINATION="OS=9.3,name=iPhone 6S Plus"

before_install:
  - gem install xcpretty -N
  - gem install slather --no-ri --no-rdoc

script:
  - set -o pipefail 
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES test | xcpretty -c

after_success:
  - slather