language: objective-c 
osx_image: xcode7.3

before_install:
  - gem install xcpretty -N
  - gem install slather --no-ri --no-rdoc

script:
  - set -o pipefail 
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild -workspace "atom-sdk/AtomSDK/AtomSDK.xcworkspace" -scheme "AtomSDK" -sdk "iphonesimulator9.3" -destination "OS=9.3,name=iPhone 6S" ONLY_ACTIVE_ARCH=YES test | xcpretty -c

after_success:
  - slather