# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AtomSDK' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AtomSDK
  pod 'sqlite3'

  target 'AtomSDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
